from pathlib import Path
import re

root = Path("winlator/app")

# Version metadata.
build = root / "app/build.gradle"
text = build.read_text(encoding="utf-8")
text = re.sub(r"versionCode\s+[^\n]+", 'versionCode Integer.parseInt("15")', text, count=1)
text = re.sub(r"versionName\s+[^\n]+", 'versionName String.valueOf("0.15.0-beta")', text, count=1)
build.write_text(text, encoding="utf-8")

for rel in [
    "app/src/main/java/com/winlator/HikariDiagnostics.java",
    "app/src/main/java/com/winlator/HikariStartupDialog.java",
    "app/src/main/java/com/winlator/HikariLauncherActivity.java",
]:
    p = root / rel
    s = p.read_text(encoding="utf-8")
    s = s.replace("0.14", "0.15")
    s = s.replace("0.13 direct Wine launch habilitado", "0.15 loader Wine real habilitado")
    p.write_text(s, encoding="utf-8")

# Wine's /opt/wine/bin/wine is only the launcher. In this RootFS the actual x86_64
# loader is /opt/wine/lib/wine/x86_64-unix/wine. Running the launcher under Box64
# fails with: "wine: could not exec the wine loader" because Android cannot exec
# the x86_64 loader directly. Launch the actual loader under Box64 instead.
guest = root / "app/src/main/java/com/winlator/xenvironment/components/GuestProgramLauncherComponent.java"
s = guest.read_text(encoding="utf-8")

old = '''            File wine64 = new File(rootDir, rootFS.getWinePath()+"/bin/wine64");
            File wine64Preloader = new File(rootDir, rootFS.getWinePath()+"/bin/wine64-preloader");
            File winePreloader = new File(rootDir, rootFS.getWinePath()+"/bin/wine-preloader");
            HikariDiagnostics.record(environment.getContext(), "wine64=" + wine64.getAbsolutePath() + " exists=" + wine64.isFile() + " size=" + (wine64.isFile() ? wine64.length() : 0));
            HikariDiagnostics.record(environment.getContext(), "wine64-preloader=" + wine64Preloader.getAbsolutePath() + " exists=" + wine64Preloader.isFile());
            HikariDiagnostics.record(environment.getContext(), "wine-preloader=" + winePreloader.getAbsolutePath() + " exists=" + winePreloader.isFile());
            File selectedWineLoader = wine64.isFile() ? wine64 : wineBinary;
            launchExecutable = selectedWineLoader.getAbsolutePath() + " cmd /c \\\"E: && cd \\\\HikariRO && raghikari.exe\\\"";
            HikariDiagnostics.record(environment.getContext(), "Wine loader seleccionado=" + selectedWineLoader.getAbsolutePath());'''

new = '''            File wine64 = new File(rootDir, rootFS.getWinePath()+"/bin/wine64");
            File wine64Preloader = new File(rootDir, rootFS.getWinePath()+"/bin/wine64-preloader");
            File winePreloader = new File(rootDir, rootFS.getWinePath()+"/bin/wine-preloader");
            File wineRealLoader = new File(rootDir, rootFS.getWinePath()+"/lib/wine/x86_64-unix/wine");
            File wineServerReal = new File(rootDir, rootFS.getWinePath()+"/bin/wineserver");
            HikariDiagnostics.record(environment.getContext(), "0.15 loader Wine real habilitado");
            HikariDiagnostics.record(environment.getContext(), "wine launcher=" + wineBinary.getAbsolutePath() + " exists=" + wineBinary.isFile() + " size=" + (wineBinary.isFile() ? wineBinary.length() : 0));
            HikariDiagnostics.record(environment.getContext(), "wine real loader=" + wineRealLoader.getAbsolutePath() + " exists=" + wineRealLoader.isFile() + " size=" + (wineRealLoader.isFile() ? wineRealLoader.length() : 0) + " exec=" + wineRealLoader.canExecute());
            HikariDiagnostics.record(environment.getContext(), "wineserver=" + wineServerReal.getAbsolutePath() + " exists=" + wineServerReal.isFile() + " size=" + (wineServerReal.isFile() ? wineServerReal.length() : 0));
            HikariDiagnostics.record(environment.getContext(), "wine64=" + wine64.getAbsolutePath() + " exists=" + wine64.isFile());
            HikariDiagnostics.record(environment.getContext(), "wine64-preloader=" + wine64Preloader.getAbsolutePath() + " exists=" + wine64Preloader.isFile());
            HikariDiagnostics.record(environment.getContext(), "wine-preloader=" + winePreloader.getAbsolutePath() + " exists=" + winePreloader.isFile());
            File selectedWineLoader = wineRealLoader.isFile() ? wineRealLoader : (wine64.isFile() ? wine64 : wineBinary);
            launchExecutable = selectedWineLoader.getAbsolutePath() + " cmd /c \\\"E: && cd \\\\HikariRO && raghikari.exe\\\"";
            HikariDiagnostics.record(environment.getContext(), "Wine loader seleccionado=" + selectedWineLoader.getAbsolutePath());'''

if old not in s:
    raise RuntimeError("No se encontro el bloque Wine loader de 0.14")
s = s.replace(old, new, 1)

guest.write_text(s, encoding="utf-8")

# Keep the 16:9 background generated by 0.14, but remove the extra dark shade
# from the launcher so the artwork fills the whole screen visibly.
for rel in [
    "app/src/main/java/com/winlator/HikariLauncherActivity.java",
    "app/src/main/java/com/winlator/HikariStartupDialog.java",
]:
    p = root / rel
    s = p.read_text(encoding="utf-8")
    s = s.replace("shade.setBackgroundColor(0x22000000);", "shade.setBackgroundColor(0x00000000);")
    p.write_text(s, encoding="utf-8")

print("0.15 patch applied: direct x86_64 Wine loader + diagnostics")
